.gitignore, build.gradle, settings.gradle, src/main/java/net/mureng/mureng/MurengBackendApplication.java, src/test/java/net/mureng/mureng/MurengBackendApplicationTests.java
Murreng --> mureng으로 프로젝트 이름 변경
=> feat: rename project

src/main/java/net/mureng/mureng/domain/question/QuestionRepository.java, src/main/java/net/mureng/mureng/domain/question/WordHintRepository.java, src/main/java/net/mureng/mureng/domain/reply/ReplyLikesRepository.java, src/main/java/net/mureng/mureng/domain/reply/ReplyRepository.java, src/test/java/net/mureng/mureng/domain/question/QuestionRepositoryTest.java, src/test/java/net/mureng/mureng/domain/question/WordHintRepositoryTest.java, src/test/resources/dbunit/entity/member.xml, src/test/resources/dbunit/entity/question.xml, src/test/resources/dbunit/entity/word_hint.xml
- 전체_질문_목록_조회
- 멤버로_질문_목록_조회
- 질문의_단어_힌트_조회
일단 이렇게 추가 했는데, 질문 저장소랑 단어힌트 저장소에서 더 필요한 테스트가 있을까??
그리고 Reply도 내가 할게!
=> Test: 질문, 단어 힌트 테스트 추가

src/main/java/net/mureng/mureng/domain/reply/ReplyLikesRepository.java, src/main/java/net/mureng/mureng/domain/reply/ReplyRepository.java, src/test/java/net/mureng/mureng/domain/reply/ReplyLikesRepositoryTest.java, src/test/java/net/mureng/mureng/domain/reply/ReplyRepositoryTest.java, src/test/resources/dbunit/entity/reply.xml, src/test/resources/dbunit/entity/reply_likes.xml
- 멤버_답변_목록_조회
- 질문_답변_목록_조회
- 답변_좋아요_수_조회
이전 꺼는 형이 준 피드백대로 수정해서 merge해놨어~
=> TEST: 답변, 답변 좋아요 테스트 작성

src/main/java/net/mureng/mureng/domain/question/TodayQuestion.java, src/main/java/net/mureng/mureng/domain/question/TodayQuestionRepository.java, src/test/java/net/mureng/mureng/domain/question/TodayQuestionRepositoryTest.java, src/test/resources/dbunit/entity/today_question.xml
Add : 오늘의 질문 엔티티 추가 #9 
- 엔티티 추가
- 엔티티 저장소 작성 & 테스트
=> Add : 오늘의 질문 엔티티 추가 (#9)

.github/workflows/gradle.yml, build.gradle, src/main/java/net/mureng/mureng/core/config/SwaggerConfig.java, src/main/java/net/mureng/mureng/core/dto/ApiResult.java, src/main/java/net/mureng/mureng/web/HomeController.java, src/test/resources/dbunit/entity/reply.xml
- API 문서화를 위해 Swagger UI 추가, 현재 기본값으로만 세팅 되어있음
- Github action workflow 추가, 이제 master변동 시 github 자체에서 gradle test 수행
- 테스트 실패한 것 수정
=> Feat: Swagger UI 추가

src/main/java/net/mureng/mureng/core/advice/DefaultControllerAdvice.java, src/main/java/net/mureng/mureng/core/config/SecurityConfig.java, src/main/java/net/mureng/mureng/core/dto/ApiResult.java, src/main/java/net/mureng/mureng/core/exception/AccessNotAllowedException.java, src/main/java/net/mureng/mureng/core/exception/BadRequestException.java, src/main/java/net/mureng/mureng/core/exception/MurengException.java, src/main/java/net/mureng/mureng/core/exception/ResourceNotFoundException.java, src/main/java/net/mureng/mureng/web/ErrorControllerImpl.java, src/main/java/net/mureng/mureng/web/HomeController.java, src/main/resources/application.properties, src/test/java/net/mureng/mureng/web/AbstractControllerTest.java, src/test/java/net/mureng/mureng/web/ErrorControllerTest.java, src/test/java/net/mureng/mureng/web/HomeControllerTest.java
- 예외 클래스 작성
- MurengException : 비즈니스 최상위 예외, 비즈니스 계층에서 발생하는 예외는 모두 이 예외 기준으로 던짐
- ResourceNotFoundException : 엔티티 등 리소스를 찾을 수 없을 때 발생하는 예외
- AccessNotAllowedException : 접근 권한 없을 때 발생하는 예외
- BadRequestException : 요청이 잘못되었을 때 발생하는 예외
- 이 이외에도 각 도메인에서 발생하는 예외는 공통 예외에서 상속받아 선언하여 만들면 됨.
- DefaultControllerAdvice 추가 => 각 예외에 맞는 응답 형태 및 코드 리턴
- 에러 컨트롤러 테스트 추가
- mockMvc 구성 단순화
Closes #33
=> [기능] 예외 기반 구축

build.gradle, src/main/java/net/mureng/mureng/core/advice/AbstractControllerAdvice.java, src/main/java/net/mureng/mureng/core/advice/DefaultControllerAdvice.java, src/main/java/net/mureng/mureng/core/advice/ValidationControllerAdvice.java, src/main/java/net/mureng/mureng/core/config/SecurityConfig.java, src/main/java/net/mureng/mureng/core/dto/ApiResult.java, src/main/java/net/mureng/mureng/core/validation/DateStringValidator.java, src/main/java/net/mureng/mureng/core/validation/TimeStringValidator.java, src/main/java/net/mureng/mureng/core/validation/annotation/DateFormat.java, src/main/java/net/mureng/mureng/core/validation/annotation/TimeFormat.java, src/main/java/net/mureng/mureng/member/component/MemberMapper.java, src/main/java/net/mureng/mureng/member/dto/MemberDto.java, src/main/java/net/mureng/mureng/member/entity/Member.java, src/main/java/net/mureng/mureng/member/entity/MemberAttendance.java, src/main/java/net/mureng/mureng/member/entity/MemberSetting.java, src/main/java/net/mureng/mureng/member/repository/MemberRepository.java, src/main/java/net/mureng/mureng/member/service/MemberService.java, src/main/java/net/mureng/mureng/member/web/MemberController.java, src/main/java/net/mureng/mureng/web/ErrorControllerImpl.java, src/main/java/net/mureng/mureng/web/HomeController.java, src/main/resources/application.properties, src/test/java/net/mureng/mureng/core/component/AbstractValidatorTest.java, src/test/java/net/mureng/mureng/core/component/DateStringValidatorTest.java, src/test/java/net/mureng/mureng/core/component/TimeStringValidatorTest.java, src/test/java/net/mureng/mureng/member/component/MemberMapperTest.java, src/test/java/net/mureng/mureng/member/repository/MemberAttendanceRepositoryTest.java, src/test/java/net/mureng/mureng/member/repository/MemberRepositoryTest.java, src/test/java/net/mureng/mureng/member/repository/MemberSettingRepositoryTest.java, src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java, src/test/java/net/mureng/mureng/web/HomeControllerTest.java
앞으로 개발은 develop 브랜치 중심으로 갈 것이며,
이 pr은 리뷰없이 병합하겠음
=> Develop 브랜치 master 기준으로 최신화

build.gradle, src/main/java/net/mureng/mureng/core/annotation/CurrentUser.java, src/main/java/net/mureng/mureng/core/component/EntityMapper.java, src/main/java/net/mureng/mureng/core/dto/UserDetailsImpl.java, src/main/java/net/mureng/mureng/member/component/MemberMapper.java, src/main/java/net/mureng/mureng/question/component/QuestionMapper.java, src/main/java/net/mureng/mureng/question/component/WordHintMapper.java, src/main/java/net/mureng/mureng/question/dto/QuestionDto.java, src/main/java/net/mureng/mureng/question/dto/WordHintDto.java, src/main/java/net/mureng/mureng/question/entity/Question.java, src/main/java/net/mureng/mureng/question/entity/TodayQuestion.java, src/main/java/net/mureng/mureng/question/entity/WordHint.java, src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java, src/main/java/net/mureng/mureng/question/repository/TodayQuestionRepository.java, src/main/java/net/mureng/mureng/question/repository/WordHintRepository.java, src/main/java/net/mureng/mureng/question/service/TodayQuestionService.java, src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java, src/test/java/net/mureng/mureng/annotation/WithMockMurengUser.java, src/test/java/net/mureng/mureng/config/WithMockMurengUserSecurityContextFactory.java, src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java, src/test/java/net/mureng/mureng/question/component/WordHintMapperTest.java, src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java, src/test/java/net/mureng/mureng/question/repository/TodayQuestionRepositoryTest.java, src/test/java/net/mureng/mureng/question/repository/WordHintRepositoryTest.java, src/test/java/net/mureng/mureng/question/web/TodayQuestionControllerTest.java, src/test/java/net/mureng/mureng/web/AbstractControllerTest.java
- 로그인한 사용자 기준으로 오늘의 질문 가져오는 엔드포인트 추가
- 시큐리티로 로그인한 사용자 가져오는 로직 추가
- 질문 DTO 및 엔티티 간 매퍼 추가
- 기타 리팩토링
Close #18
=> [기능] 오늘의 질문 가져오기

src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java, src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/entity/Reply.java, src/main/java/net/mureng/mureng/reply/entity/ReplyLikes.java, src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java, src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java, src/test/resources/dbunit/entity/reply.xml
- Reply Dto 및 매퍼 작성
- 답변 작성 엔드포인트 추가(Question Service 추가)
- 엔드포인트 관련 테스트
=> [기능] 답변 작성하기

src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/entity/Reply.java, src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java, src/test/java/net/mureng/mureng/reply/service/ReplyServiceTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
이런식으로 코드를 작성했는데, setter로 해도 괜찮겠지..???
그리고일단 일부만 바꾼단 생각에 PatchMapping으로 해두었는데, PutMapping이 더 나을까??
=> [기능] 답변 수정하기 및 삭제하기

.github/workflows/test-and-deploy-dev.yaml, .gitignore, deployment/deployment-dev.yml, src/main/java/net/mureng/mureng/core/component/FileUploader.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/main/resources/application.yml, src/test/java/net/mureng/mureng/core/component/FileUploaderTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
- 파일 업로드 구현
- 미디어 서버로서 이미지를 제공할 수 있도록 Apache 컨테이너 추가
- 관련 테스트 추가
=> [기능] 파일 업로드 구현 및 매니페스트 파일에 httpd 컨테이너 추가

src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/question/web/QuestionController.java, src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/common/EntityCreator.java, src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java, src/test/java/net/mureng/mureng/reply/service/ReplyServiceTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
질문 페이징 목록 조회 기능 추가
정렬을 사용한 페이징 할 예정!
=> [기능] 질문 페이징 목록 조회 

src/main/java/net/mureng/mureng/core/dto/ApiPageRequest.java, src/main/java/net/mureng/mureng/core/dto/ApiPageResult.java, src/main/java/net/mureng/mureng/core/dto/ApiResult.java, src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java, src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/question/web/QuestionController.java, src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/entity/Reply.java, src/main/java/net/mureng/mureng/reply/entity/ReplyLikes.java, src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/test/java/net/mureng/mureng/common/EntityCreator.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java, src/test/java/net/mureng/mureng/reply/repository/ReplyRepositoryTest.java, src/test/resources/dbunit/entity/reply.xml
질문에 연관된 답변 조회하는 엔드포인트 추가 및 관련 테스트 추가
슬슬 속도 내야겠다..!!!
Closes #27
=> [기능] 질문 연관 답변 조회 추가

src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/main/java/net/mureng/mureng/reply/web/ReplyImageController.java
- 현재 에셋을 못받은 관계로 임시 더미 목록을 리턴한다.
=> [기능] 기본 이미지 목록 받아오는 엔드포인트 추가

src/main/java/net/mureng/mureng/core/component/NumberRandomizer.java, src/main/java/net/mureng/mureng/question/entity/TodayQuestion.java, src/main/java/net/mureng/mureng/question/service/TodayQuestionSelectionService.java, src/main/java/net/mureng/mureng/question/service/TodayQuestionSelectionServiceImpl.java, src/main/java/net/mureng/mureng/question/service/TodayQuestionService.java, src/main/java/net/mureng/mureng/question/web/TodayQuestionController.java, src/test/java/net/mureng/mureng/question/service/TodayQuestionSelectionServiceImplTest.java, src/test/java/net/mureng/mureng/question/web/TodayQuestionControllerTest.java
- 오늘의 질문 새로고침
- 이미 답변한 내용은 제외, 그러나 만약 모두 답변을 했을 경우 새로고침 이전 동일한 질문 출력
=> [기능] 오늘의 질문 새로고침하는 엔드포인트 추가

src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/repository/ReplyRepository.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
전체 답변 목록을 조회할 수 있다.
page, size, sort 옵션을 통해 인기 답변 조회에도 활용 가능하다.
=> [기능] 답변 목록 조회 추가

src/main/java/net/mureng/mureng/question/web/QuestionController.java, src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java, src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java
- 프론트 요청으로 특정 질문에 대해서 내가 답변한 질문 가져오는 엔드포인트 추가
- 만약 답변이 존재하지 않는다면 404 응답
=> [기능] 질문에 대한 내 답변 가져오기 엔드포인트 추가

src/main/java/net/mureng/mureng/member/web/MemberController.java, src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/test/java/net/mureng/mureng/common/EntityCreator.java, src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java, src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java
엔드포인트 추가
- 사용자가 작성한 답변 목록 조회하기 api/member/replies
- 사용자가 오늘 답변 했는 지 확인하기 api/member/check-replied
두개 엔드포인트 추가했고, 전에 replyMapper 테스트 추가하라는거 그 때 안했어서...ㅎ 이제 추가합니당..
=> [기능] 사용자 답변 목록, 사용자 오늘 답변 유무 엔드포인트 추가

src/main/java/net/mureng/mureng/core/dto/ApiPageRequest.java, src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/question/web/QuestionController.java, src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java, src/main/java/net/mureng/mureng/reply/service/ReplyService.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java, src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
=> [보완] 페이징에서 정렬 값 enum으로 변경

src/main/java/net/mureng/mureng/question/web/QuestionReplyController.java, src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/main/java/net/mureng/mureng/reply/web/ReplyController.java, src/test/java/net/mureng/mureng/common/EntityCreator.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java, src/test/java/net/mureng/mureng/question/web/QuestionReplyControllerTest.java, src/test/java/net/mureng/mureng/reply/component/ReplyMapperTest.java, src/test/java/net/mureng/mureng/reply/web/ReplyControllerTest.java
- 프론트 요청으로 이 답변이 로그인한 사용자 본인인지 검증할 수 있는 requestedByAuthor 필드를 추가했다.
=> [기능] ReplyDto 에 requestedByAuthor 필드 추가, 관련 매퍼 수정

src/main/java/net/mureng/mureng/question/component/QuestionMapper.java, src/main/java/net/mureng/mureng/question/entity/Question.java, src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/question/web/QuestionController.java, src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java, src/test/java/net/mureng/mureng/question/web/QuestionControllerTest.java
질문 등록하기 기능 추가했어!
그리고 ko_content같은 경우, 빈 값으로 제공될 수도 있는 거 같아서, null가능으로 다시 바꿨어!
=> [기능] 질문 등록하기

src/main/java/net/mureng/mureng/member/service/MemberService.java, src/main/java/net/mureng/mureng/member/web/MemberController.java, src/test/java/net/mureng/mureng/member/web/MemberControllerTest.java
사용자의 프로필 정보를 가져올 수 있다.
/api/member/{memerId}
=> [기능] 사용자 프로필 정보 가져오기

src/main/java/net/mureng/mureng/member/dto/MemberDto.java, src/main/java/net/mureng/mureng/question/component/QuestionMapper.java, src/main/java/net/mureng/mureng/question/dto/QuestionDto.java, src/main/java/net/mureng/mureng/question/dto/WordHintDto.java, src/main/java/net/mureng/mureng/question/entity/Question.java, src/main/java/net/mureng/mureng/question/repository/QuestionRepository.java, src/main/java/net/mureng/mureng/question/service/QuestionService.java, src/main/java/net/mureng/mureng/reply/component/ReplyMapper.java, src/main/java/net/mureng/mureng/reply/dto/ReplyDto.java, src/test/java/net/mureng/mureng/common/EntityCreator.java, src/test/java/net/mureng/mureng/question/component/QuestionMapperTest.java, src/test/java/net/mureng/mureng/question/repository/QuestionRepositoryTest.java, src/test/java/net/mureng/mureng/question/web/TodayQuestionControllerTest.java
- 프론트 요청으로 질문 가져올 때 작성자 정보 추가 (시스템에서 작성한 경우 null)
- DTO 프로퍼티 순서 조정하는 내부 정적 클래스 추가
=> [기능] 질문 가져오기에서 작성자 정보 추가

.github/workflows/gradle-test.yml, .github/workflows/test-and-deploy-dev.yaml, Dockerfile, deployment/deployment-dev.yml, gradle/wrapper/gradle-wrapper.properties
- Github action 레벨에서 시간이 많이 걸리는 부분을 최적화, 자체 테스트 결과 1~2분 가량 줄어듬
- Pod 에 할당한 자원량 증가
=> [보완] github-action 캐싱 사용하여 배포 속도 향상

mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java, mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java, mureng-api/src/main/java/net/mureng/api/reply/service/ReplyImageService.java, mureng-api/src/main/java/net/mureng/api/reply/service/ReplyPaginationService.java, mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java, mureng-api/src/test/java/net/mureng/api/reply/component/ReplyMapperTest.java, mureng-core/src/main/java/net/mureng/core/reply/entity/Reply.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java, mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
- ReplyDto에 likedByMember 추가
- Reply 엔티티에 isWriter -> isAuthor로 변경 및 requestedByAuthor 값 설정할 때 사용하도록 변경
=> [보완] ReplyDto에 likedByMember 추가

mureng-api/src/main/java/net/mureng/api/core/dto/ApiPageResult.java, mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java, mureng-core/src/test/resources/dbunit/entity/reply.xml
- PageResult에 totalElements 추가
=> [보완] PageResult 전체 요소 개수 추가

mureng-api/src/main/java/net/mureng/api/reply/component/ReplyLikesMapper.java, mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java, mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java, mureng-api/src/main/java/net/mureng/api/todayexpression/web/TodayExpressionController.java, mureng-api/src/test/java/net/mureng/api/common/DtoCreator.java, mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java, mureng-api/src/test/java/net/mureng/api/todayexpression/web/TodayExpressionControllerTest.java, mureng-core/src/main/java/net/mureng/core/todayexpression/entity/TodayExpression.java, mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java, mureng-core/src/test/java/net/mureng/core/common/EntityCreator.java
- 오늘의 표현 가져오기 엔드포인트 추가
- 컨트롤러 테스트 구현
- 요청자가 해당 표현을 이미 스크랩했는 지는 #90 구현 이후에 추가할 예정
=> [기능] 오늘의 표현 가져오기

mureng-api/src/main/java/net/mureng/api/reply/service/ReplyImageService.java, mureng-api/src/main/java/net/mureng/api/reply/web/ReplyImageController.java, mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java, mureng-api/src/test/java/net/mureng/api/reply/web/ReplyImageControllerTest.java, mureng-core/src/main/java/net/mureng/core/core/component/DirectoryScanner.java
기본이미지 목록 API -> 더미 이미지 경로를 사전에 올려둔 실제 기본 이미지 경로로 변경
=> [기능] 기본 이미지 목록 더미 제거, 실제 디렉토리 스캔으로 변경

mureng-core/src/main/resources/application-dev-local.yml, mureng-core/src/main/resources/config/liquibase/changelog/20200527_add_unique_constraint.xml, mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyRepositoryTest.java
- member_id, question_id 조합 중복 방지 (하나의 질문에 한 사람이 두번 답변을 달 수 없다)
=> [추가] Reply 테이블에 Unique 제약조건 추가

mureng-api/src/main/java/net/mureng/api/member/service/MemberImageService.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberImageController.java, mureng-api/src/main/java/net/mureng/api/reply/web/ReplyImageController.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberImageControllerTest.java
- 답변 이미지 업로드와 방식은 거의 동일, 경로만 살짝 다르다.
=> [기능] 회원 이미지 업로드 기능 추가

mureng-api/src/main/java/net/mureng/api/question/dto/QuestionDto.java, mureng-api/src/test/java/net/mureng/api/question/component/QuestionDtoValidationTest.java
=> [보완] 질문 최대 글자수 검증 로직 추가

mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java, mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
=> [기능] OAuth 사용자 프로필 가져오기

mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java
=> [수정] page to 0

mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java, mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
- oAuthService equals로 수정
- 서비스 테스트 `@Ignore` 추가
=> [수정] oauthService 수정

mureng-core/src/main/java/net/mureng/core/reply/entity/ReplyLikesPK.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java, mureng-core/src/test/java/net/mureng/core/reply/repository/ReplyLikesRepositoryTest.java
=> [수정] 답변 좋아요

mureng-core/src/main/java/net/mureng/core/reply/entity/ReplyLikes.java
- all로 설정된 탓에, replylikes를 삭제할 시, reply 엔티티가 삭제되는 현상이 발생함
=> [버그] 좋아요 취소 시 답변 삭제

mureng-api/src/test/java/net/mureng/api/oauth/OAuthServiceTest.java
- Junit5에서 Ignore은 Disabled로 변경됨
=> [수정] 테스트 실패

mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtCreator.java, mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtResolver.java, mureng-api/src/main/java/net/mureng/api/core/jwt/service/JwtService.java, mureng-api/src/main/java/net/mureng/api/core/jwt/web/JwtController.java, mureng-api/src/main/java/net/mureng/api/core/oauth2/dto/OAuth2Profile.java, mureng-api/src/main/java/net/mureng/api/core/oauth2/service/OAuth2Service.java, mureng-api/src/main/java/net/mureng/api/member/dto/MemberDto.java, mureng-api/src/main/java/net/mureng/api/member/service/UserDetailsServiceImpl.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java, mureng-api/src/test/java/net/mureng/api/jwt/JwtAuthenticationTest.java, mureng-api/src/test/java/net/mureng/api/oauth/OAuthTest.java, mureng-core/src/main/java/net/mureng/core/member/entity/Member.java, mureng-core/src/main/java/net/mureng/core/member/repository/MemberRepository.java, mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java
- 사용자 식별을 email에서 identifier로 변경
=> [수정] 사용자 식별을 email에서 identifier로 변경

mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java, mureng-core/src/main/java/net/mureng/core/badge/repository/BadgeAccomplishedRepository.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedService.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeService.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java, mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
- 머렝3일
- 셀럽머렝
- 학구적머렝
- 머렝셋(쿠키30개) 
뱃지 획득 로직 작성
=> [기능] 뱃지 획득

mureng-api/src/main/java/net/mureng/api/member/service/MemberSignupService.java, mureng-api/src/main/java/net/mureng/api/member/service/UserDetailsServiceImpl.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java, mureng-core/src/main/java/net/mureng/core/member/entity/Member.java, mureng-core/src/main/java/net/mureng/core/member/repository/MemberRepository.java, mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java, mureng-core/src/test/java/net/mureng/core/member/repository/MemberRepositoryTest.java, mureng-core/src/test/resources/dbunit/entity/member.xml, mureng-core/src/test/resources/dbunit/expected/멤버_머렝_카운트_증가.xml
- 탈퇴라고 해도 사실상 비활성화 개념
- 만약 탈퇴한 사람이 재가입 했을 경우, 비활성화를 다시 푼다.
=> Add: 회원가입 탈퇴 로직 작성

mureng-api/src/main/java/net/mureng/api/web/FcmTokenController.java, mureng-core/src/main/java/net/mureng/core/member/repository/FcmTokenRepository.java, mureng-core/src/main/java/net/mureng/core/member/service/FcmTokenService.java, mureng-core/src/main/java/net/mureng/push/service/FcmLikePushServiceImpl.java
findByMember -> findByMemberMemberId로 변경
=> [수정] Fcm Token 설정

mureng-api/src/main/java/net/mureng/api/member/service/MemberExpressionScrapService.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberScrapController.java, mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java, mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java, mureng-api/src/main/java/net/mureng/api/reply/web/ReplyController.java, mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java, mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberScrapControllerTest.java, mureng-api/src/test/java/net/mureng/api/reply/component/ReplyMapperTest.java, mureng-api/src/test/java/net/mureng/api/reply/web/ReplyControllerTest.java, mureng-api/src/test/java/net/mureng/api/todayexpression/component/TodayExpressionMapperTest.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java, mureng-core/src/main/java/net/mureng/core/member/repository/MemberScrapRepository.java, mureng-core/src/main/java/net/mureng/core/reply/repository/ReplyRepository.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java, mureng-core/src/test/java/net/mureng/core/badge/repository/BadgeAccomplishedRepositoryTest.java, mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
celebrity 뱃지 빼곤 다 구현했는데, Entity에 필드 추가하니까 자꾸 에러가 나더라고. 혹시 내가 뭔가 해줘야해??
=> [기능] 뱃지 팝업 Response

mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java, mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java, mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java, mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java
=> [수정] 매퍼 에러 

mureng-api/src/main/java/net/mureng/api/member/component/MemberAchievementMapper.java, mureng-api/src/main/java/net/mureng/api/member/dto/MemberAchievementDto.java, mureng-api/src/main/java/net/mureng/api/member/service/MemberBadgeService.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberAchievementController.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberBadgeController.java, mureng-api/src/main/java/net/mureng/api/reply/component/ReplyMapper.java, mureng-api/src/main/java/net/mureng/api/reply/dto/ReplyDto.java, mureng-api/src/main/java/net/mureng/api/todayexpression/component/TodayExpressionMapper.java, mureng-api/src/main/java/net/mureng/api/todayexpression/dto/TodayExpressionDto.java, mureng-api/src/test/java/net/mureng/api/member/component/MemberAchievementMapperTest.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberAchievementControllerTest.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberBadgeController.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberBadgeControllerTest.java, mureng-core/src/main/java/net/mureng/core/badge/entity/BadgeAccomplished.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedService.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyLikesService.java, mureng-core/src/main/resources/config/liquibase/changelog/20210622_add_badge_is_checked_field.xml
=> [기능] 셀럽머렝 추가

mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java, mureng-core/src/main/java/net/mureng/core/badge/service/BadgeService.java, mureng-core/src/main/java/net/mureng/core/core/component/DirectoryScanner.java, mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java, mureng-core/src/main/java/net/mureng/core/member/service/MemberService.java, mureng-core/src/main/java/net/mureng/core/question/service/QuestionService.java, mureng-core/src/main/java/net/mureng/core/question/service/TodayQuestionSelectionServiceImpl.java, mureng-core/src/main/java/net/mureng/core/question/service/TodayQuestionService.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyPostProcessServiceImpl.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyService.java, mureng-core/src/main/java/net/mureng/core/todayexpression/service/TodayExpressionService.java, mureng-core/src/test/java/net/mureng/core/reply/service/ReplyPostProcessServiceImplTest.java, mureng-core/src/test/java/net/mureng/core/reply/service/ReplyServiceTest.java
- 서비스단 에러 메시지를 ErrorMessage 클래스에서 관리하도록 변경
- PostProcess에서 increaseMurengCount가 DB에 반영되지 않던 것을 수정
=> [리팩토링] 서비스단 에러 메시지 및 PostProcess 버그 수정

mureng-core/src/main/java/net/mureng/core/badge/service/BadgeAccomplishedServiceImpl.java
=> Fix: 머렝 쿠키 관련 뱃지 획득 조건 변경

mureng-core/src/main/java/net/mureng/core/cookie/repository/CookieAcquirementRepository.java, mureng-core/src/main/java/net/mureng/core/cookie/service/CookieAcquirementService.java, mureng-core/src/main/java/net/mureng/core/core/message/ErrorMessage.java, mureng-core/src/main/java/net/mureng/core/reply/service/ReplyPostProcessServiceImpl.java, mureng-core/src/test/java/net/mureng/core/cookie/repository/CookieAcquirementRepositoryTest.java, mureng-core/src/test/resources/dbunit/entity/cookie_acquirement.xml
글을 삭제하고 다시 작성할 경우, 쿠키를 중복해서 획득하는 문제가 발생
쿠키 테이블을 조회해, 쿠키 중복 획득 문제를 해결
=> [수정] 쿠키 중복 획득 처리 해결

mureng-api/src/main/java/net/mureng/api/core/component/RequestLogFilter.java, mureng-core/src/main/resources/application.yml
https://velog.io/@sixhustle/log 코드 복붙 ㅎ..
Closes #171
=> feat: 요청 및 응답 로깅 추가, 로깅 레벨 조정

.github/workflows/gradle-test.yml, .github/workflows/test-and-deploy-app-prod.yaml, .github/workflows/test-and-deploy-batch-prod.yaml, .github/workflows/test-and-deploy-dev.yaml, build.gradle, mureng-api/src/main/java/net/mureng/api/core/component/AttendanceCheckInterceptor.java, mureng-api/src/main/java/net/mureng/api/core/config/HttpConfig.java, mureng-api/src/main/java/net/mureng/api/core/config/SecurityConfig.java, mureng-api/src/main/java/net/mureng/api/core/dto/UserDetailsImpl.java, mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtAuthenticationFilter.java, mureng-api/src/main/java/net/mureng/api/core/jwt/component/JwtResolver.java, mureng-api/src/main/java/net/mureng/api/core/util/AuthenticationHelper.java, mureng-api/src/main/java/net/mureng/api/member/web/MemberController.java, mureng-api/src/test/java/net/mureng/api/config/WithMockMurengUserSecurityContextFactory.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberAuthControllerTest.java, mureng-api/src/test/java/net/mureng/api/member/web/MemberControllerTest.java, mureng-api/src/test/java/net/mureng/api/web/HomeControllerTest.java, mureng-core/src/main/java/net/mureng/core/member/entity/Member.java
인터셉터를 활용해서 하루에 한 번, 출석체크를 진행할 수 있도록 했다.
=> [추가] 출석체크 로직 추가 및 관련 테스트 추가

build.gradle
각 모듈의 test coverage 확인을 위한 jacoco 설치
=> jacoco 라이브러리 설치
